version: "3.8"
services:
  devcontainer:
    hostname: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - 80:8080
    tty: true
